# **This section will contain the code operations on the raw dataset.**

In [1]:
# Importing all the required libraries:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 
print("All required libraries are imported successfully!")

All required libraries are imported successfully!

In [2]:
# Loading the dataset:
train_transaction = pd.read_csv(r'C:\Users\acer\Desktop\Programs\Projects_for _data_science\Fraud_Detection_Model\data\01_raw\train_transaction.csv')

In [3]:
# Overview of the dataset:
train_transaction.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
#Summary of the dataset:
train_transaction.info()

<class 'pandas.DataFrame'>
RangeIndex: 590540 entries, 0 to 590539
Columns: 394 entries, TransactionID to V339
dtypes: float64(376), int64(4), str(14)
memory usage: 1.7 GB

In [5]:
# Shape of the dataset:
train_transaction.shape

(590540, 394)

In [6]:
# Data Types of the dataset:
train_transaction.dtypes

TransactionID       int64
isFraud             int64
TransactionDT       int64
TransactionAmt    float64
ProductCD             str
                   ...
V335              float64
V336              float64
V337              float64
V338              float64
V339              float64
Length: 394, dtype: object

In [7]:
# Statistical summary of the dataset:
train_transaction.describe()

,TransactionID,isFraud,TransactionDT,TransactionAmt,card1,card2,card3,card5,addr1,addr2,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
count,5.905400e+05,590540.000000,5.905400e+05,590540.000000,590540.000000,581607.000000,588975.000000,586281.000000,524834.000000,524834.000000,...,82351.000000,82351.000000,82351.000000,82351.000000,82351.000000,82351.00000,82351.000000,82351.000000,82351.000000,82351.000000
mean,3.282270e+06,0.034990,7.372311e+06,135.027176,9898.734658,362.555488,153.194925,199.278897,290.733794,86.800630,...,0.775874,721.741883,1375.783644,1014.622782,9.807015,59.16455,28.530903,55.352422,151.160542,100.700882
std,1.704744e+05,0.183755,4.617224e+06,239.162522,4901.170153,157.793246,11.336444,41.244453,101.741072,2.690623,...,4.727971,6217.223583,11169.275702,7955.735482,243.861391,387.62948,274.576920,668.486833,1095.034387,814.946722
min,2.987000e+06,0.000000,8.640000e+04,0.251000,1000.000000,100.000000,100.000000,100.000000,100.000000,10.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,3.134635e+06,0.000000,3.027058e+06,43.321000,6019.000000,214.000000,150.000000,166.000000,204.000000,87.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
50%,3.282270e+06,0.000000,7.306528e+06,68.769000,9678.000000,361.000000,150.000000,226.000000,299.000000,87.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
75%,3.429904e+06,0.000000,1.124662e+07,125.000000,14184.000000,512.000000,150.000000,226.000000,330.000000,87.000000,...,0.000000,0.000000,25.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
max,3.577539e+06,1.000000,1.581113e+07,31937.391000,18396.000000,600.000000,231.000000,237.000000,540.000000,102.000000,...,55.000000,160000.000000,160000.000000,160000.000000,55125.000000,55125.00000,55125.000000,104060.000000,104060.000000,104060.000000

In [8]:
# columns of the dataset:
train_transaction.columns.tolist()

['TransactionID',
 'isFraud',
 'TransactionDT',
 'TransactionAmt',
 'ProductCD',
 'card1',
 'card2',
 'card3',
 'card4',
 'card5',
 'card6',
 'addr1',
 'addr2',
 'dist1',
 'dist2',
 'P_emaildomain',
 'R_emaildomain',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C8',
 'C9',
 'C10',
 'C11',
 'C12',
 'C13',
 'C14',
 'D1',
 'D2',
 'D3',
 'D4',
 'D5',
 'D6',
 'D7',
 'D8',
 'D9',
 'D10',
 'D11',
 'D12',
 'D13',
 'D14',
 'D15',
 'M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'M7',
 'M8',
 'M9',
 'V1',
 'V2',
 'V3',
 'V4',
 'V5',
 'V6',
 'V7',
 'V8',
 'V9',
 'V10',
 'V11',
 'V12',
 'V13',
 'V14',
 'V15',
 'V16',
 'V17',
 'V18',
 'V19',
 'V20',
 'V21',
 'V22',
 'V23',
 'V24',
 'V25',
 'V26',
 'V27',
 'V28',
 'V29',
 'V30',
 'V31',
 'V32',
 'V33',
 'V34',
 'V35',
 'V36',
 'V37',
 'V38',
 'V39',
 'V40',
 'V41',
 'V42',
 'V43',
 'V44',
 'V45',
 'V46',
 'V47',
 'V48',
 'V49',
 'V50',
 'V51',
 'V52',
 'V53',
 'V54',
 'V55',
 'V56',
 'V57',
 'V58',
 'V59',
 'V60',
 'V61',
 'V62',
 'V63',
 'V64',
 'V65',
 'V66',
 'V67',
 'V68',
 'V69',
 'V70',
 'V71',
 'V72',
 'V73',
 'V74',
 'V75',
 'V76',
 'V77',
 'V78',
 'V79',
 'V80',
 'V81',
 'V82',
 'V83',
 'V84',
 'V85',
 'V86',
 'V87',
 'V88',
 'V89',
 'V90',
 'V91',
 'V92',
 'V93',
 'V94',
 'V95',
 'V96',
 'V97',
 'V98',
 'V99',
 'V100',
 'V101',
 'V102',
 'V103',
 'V104',
 'V105',
 'V106',
 'V107',
 'V108',
 'V109',
 'V110',
 'V111',
 'V112',
 'V113',
 'V114',
 'V115',
 'V116',
 'V117',
 'V118',
 'V119',
 'V120',
 'V121',
 'V122',
 'V123',
 'V124',
 'V125',
 'V126',
 'V127',
 'V128',
 'V129',
 'V130',
 'V131',
 'V132',
 'V133',
 'V134',
 'V135',
 'V136',
 'V137',
 'V138',
 'V139',
 'V140',
 'V141',
 'V142',
 'V143',
 'V144',
 'V145',
 'V146',
 'V147',
 'V148',
 'V149',
 'V150',
 'V151',
 'V152',
 'V153',
 'V154',
 'V155',
 'V156',
 'V157',
 'V158',
 'V159',
 'V160',
 'V161',
 'V162',
 'V163',
 'V164',
 'V165',
 'V166',
 'V167',
 'V168',
 'V169',
 'V170',
 'V171',
 'V172',
 'V173',
 'V174',
 'V175',
 'V176',
 'V177',
 'V178',
 'V179',
 'V180',
 'V181',
 'V182',
 'V183',
 'V184',
 'V185',
 'V186',
 'V187',
 'V188',
 'V189',
 'V190',
 'V191',
 'V192',
 'V193',
 'V194',
 'V195',
 'V196',
 'V197',
 'V198',
 'V199',
 'V200',
 'V201',
 'V202',
 'V203',
 'V204',
 'V205',
 'V206',
 'V207',
 'V208',
 'V209',
 'V210',
 'V211',
 'V212',
 'V213',
 'V214',
 'V215',
 'V216',
 'V217',
 'V218',
 'V219',
 'V220',
 'V221',
 'V222',
 'V223',
 'V224',
 'V225',
 'V226',
 'V227',
 'V228',
 'V229',
 'V230',
 'V231',
 'V232',
 'V233',
 'V234',
 'V235',
 'V236',
 'V237',
 'V238',
 'V239',
 'V240',
 'V241',
 'V242',
 'V243',
 'V244',
 'V245',
 'V246',
 'V247',
 'V248',
 'V249',
 'V250',
 'V251',
 'V252',
 'V253',
 'V254',
 'V255',
 'V256',
 'V257',
 'V258',
 'V259',
 'V260',
 'V261',
 'V262',
 'V263',
 'V264',
 'V265',
 'V266',
 'V267',
 'V268',
 'V269',
 'V270',
 'V271',
 'V272',
 'V273',
 'V274',
 'V275',
 'V276',
 'V277',
 'V278',
 'V279',
 'V280',
 'V281',
 'V282',
 'V283',
 'V284',
 'V285',
 'V286',
 'V287',
 'V288',
 'V289',
 'V290',
 'V291',
 'V292',
 'V293',
 'V294',
 'V295',
 'V296',
 'V297',
 'V298',
 'V299',
 'V300',
 'V301',
 'V302',
 'V303',
 'V304',
 'V305',
 'V306',
 'V307',
 'V308',
 'V309',
 'V310',
 'V311',
 'V312',
 'V313',
 'V314',
 'V315',
 'V316',
 'V317',
 'V318',
 'V319',
 'V320',
 'V321',
 'V322',
 'V323',
 'V324',
 'V325',
 'V326',
 'V327',
 'V328',
 'V329',
 'V330',
 'V331',
 'V332',
 'V333',
 'V334',
 'V335',
 'V336',
 'V337',
 'V338',
 'V339']

In [9]:
train_transaction.isnull()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590535,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,True,True,True,True,True,True
590536,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
590537,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
590538,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
590539,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True

In [10]:
for i in train_transaction.columns:
    print(f"Column: {i} | Missing Values: {train_transaction[i].isnull().sum() } | Percentage: {train_transaction[i].isnull().mean()*100:.2f}%")

Column: TransactionID | Missing Values: 0 | Percentage: 0.00%
Column: isFraud | Missing Values: 0 | Percentage: 0.00%
Column: TransactionDT | Missing Values: 0 | Percentage: 0.00%
Column: TransactionAmt | Missing Values: 0 | Percentage: 0.00%
Column: ProductCD | Missing Values: 0 | Percentage: 0.00%
Column: card1 | Missing Values: 0 | Percentage: 0.00%
Column: card2 | Missing Values: 8933 | Percentage: 1.51%
Column: card3 | Missing Values: 1565 | Percentage: 0.27%
Column: card4 | Missing Values: 1577 | Percentage: 0.27%
Column: card5 | Missing Values: 4259 | Percentage: 0.72%
Column: card6 | Missing Values: 1571 | Percentage: 0.27%
Column: addr1 | Missing Values: 65706 | Percentage: 11.13%
Column: addr2 | Missing Values: 65706 | Percentage: 11.13%
Column: dist1 | Missing Values: 352271 | Percentage: 59.65%
Column: dist2 | Missing Values: 552913 | Percentage: 93.63%
Column: P_emaildomain | Missing Values: 94456 | Percentage: 15.99%
Column: R_emaildomain | Missing Values: 453249 | Percentage: 76.75%
Column: C1 | Missing Values: 0 | Percentage: 0.00%
Column: C2 | Missing Values: 0 | Percentage: 0.00%
Column: C3 | Missing Values: 0 | Percentage: 0.00%
Column: C4 | Missing Values: 0 | Percentage: 0.00%
Column: C5 | Missing Values: 0 | Percentage: 0.00%
Column: C6 | Missing Values: 0 | Percentage: 0.00%
Column: C7 | Missing Values: 0 | Percentage: 0.00%
Column: C8 | Missing Values: 0 | Percentage: 0.00%
Column: C9 | Missing Values: 0 | Percentage: 0.00%
Column: C10 | Missing Values: 0 | Percentage: 0.00%
Column: C11 | Missing Values: 0 | Percentage: 0.00%
Column: C12 | Missing Values: 0 | Percentage: 0.00%
Column: C13 | Missing Values: 0 | Percentage: 0.00%
Column: C14 | Missing Values: 0 | Percentage: 0.00%
Column: D1 | Missing Values: 1269 | Percentage: 0.21%
Column: D2 | Missing Values: 280797 | Percentage: 47.55%
Column: D3 | Missing Values: 262878 | Percentage: 44.51%
Column: D4 | Missing Values: 168922 | Percentage: 28.60%
Column: D5 | Missing Values: 309841 | Percentage: 52.47%
Column: D6 | Missing Values: 517353 | Percentage: 87.61%
Column: D7 | Missing Values: 551623 | Percentage: 93.41%
Column: D8 | Missing Values: 515614 | Percentage: 87.31%
Column: D9 | Missing Values: 515614 | Percentage: 87.31%
Column: D10 | Missing Values: 76022 | Percentage: 12.87%
Column: D11 | Missing Values: 279287 | Percentage: 47.29%
Column: D12 | Missing Values: 525823 | Percentage: 89.04%
Column: D13 | Missing Values: 528588 | Percentage: 89.51%
Column: D14 | Missing Values: 528353 | Percentage: 89.47%
Column: D15 | Missing Values: 89113 | Percentage: 15.09%
Column: M1 | Missing Values: 271100 | Percentage: 45.91%
Column: M2 | Missing Values: 271100 | Percentage: 45.91%
Column: M3 | Missing Values: 271100 | Percentage: 45.91%
Column: M4 | Missing Values: 281444 | Percentage: 47.66%
Column: M5 | Missing Values: 350482 | Percentage: 59.35%
Column: M6 | Missing Values: 169360 | Percentage: 28.68%
Column: M7 | Missing Values: 346265 | Percentage: 58.64%
Column: M8 | Missing Values: 346252 | Percentage: 58.63%
Column: M9 | Missing Values: 346252 | Percentage: 58.63%
Column: V1 | Missing Values: 279287 | Percentage: 47.29%
Column: V2 | Missing Values: 279287 | Percentage: 47.29%
Column: V3 | Missing Values: 279287 | Percentage: 47.29%
Column: V4 | Missing Values: 279287 | Percentage: 47.29%
Column: V5 | Missing Values: 279287 | Percentage: 47.29%
Column: V6 | Missing Values: 279287 | Percentage: 47.29%
Column: V7 | Missing Values: 279287 | Percentage: 47.29%
Column: V8 | Missing Values: 279287 | Percentage: 47.29%
Column: V9 | Missing Values: 279287 | Percentage: 47.29%
Column: V10 | Missing Values: 279287 | Percentage: 47.29%
Column: V11 | Missing Values: 279287 | Percentage: 47.29%
Column: V12 | Missing Values: 76073 | Percentage: 12.88%
Column: V13 | Missing Values: 76073 | Percentage: 12.88%
Column: V14 | Missing Values: 76073 | Percentage: 12.88%
Column: V15 | Missing Values: 76073 | Percentage: 12.88%
Column: V16 | Missing Values: 76073 | Percentage: 12.88%
Column: V17 | Missing Values: 76073 | Percentage: 12.88%
Column: V18 | Missing Values: 76073 | Percentage: 12.88%
Column: V19 | Missing Values: 76073 | Percentage: 12.88%
Column: V20 | Missing Values: 76073 | Percentage: 12.88%
Column: V21 | Missing Values: 76073 | Percentage: 12.88%
Column: V22 | Missing Values: 76073 | Percentage: 12.88%
Column: V23 | Missing Values: 76073 | Percentage: 12.88%
Column: V24 | Missing Values: 76073 | Percentage: 12.88%
Column: V25 | Missing Values: 76073 | Percentage: 12.88%
Column: V26 | Missing Values: 76073 | Percentage: 12.88%
Column: V27 | Missing Values: 76073 | Percentage: 12.88%
Column: V28 | Missing Values: 76073 | Percentage: 12.88%
Column: V29 | Missing Values: 76073 | Percentage: 12.88%
Column: V30 | Missing Values: 76073 | Percentage: 12.88%
Column: V31 | Missing Values: 76073 | Percentage: 12.88%
Column: V32 | Missing Values: 76073 | Percentage: 12.88%
Column: V33 | Missing Values: 76073 | Percentage: 12.88%
Column: V34 | Missing Values: 76073 | Percentage: 12.88%
Column: V35 | Missing Values: 168969 | Percentage: 28.61%
Column: V36 | Missing Values: 168969 | Percentage: 28.61%
Column: V37 | Missing Values: 168969 | Percentage: 28.61%
Column: V38 | Missing Values: 168969 | Percentage: 28.61%
Column: V39 | Missing Values: 168969 | Percentage: 28.61%
Column: V40 | Missing Values: 168969 | Percentage: 28.61%
Column: V41 | Missing Values: 168969 | Percentage: 28.61%
Column: V42 | Missing Values: 168969 | Percentage: 28.61%
Column: V43 | Missing Values: 168969 | Percentage: 28.61%
Column: V44 | Missing Values: 168969 | Percentage: 28.61%
Column: V45 | Missing Values: 168969 | Percentage: 28.61%
Column: V46 | Missing Values: 168969 | Percentage: 28.61%
Column: V47 | Missing Values: 168969 | Percentage: 28.61%
Column: V48 | Missing Values: 168969 | Percentage: 28.61%
Column: V49 | Missing Values: 168969 | Percentage: 28.61%
Column: V50 | Missing Values: 168969 | Percentage: 28.61%
Column: V51 | Missing Values: 168969 | Percentage: 28.61%
Column: V52 | Missing Values: 168969 | Percentage: 28.61%
Column: V53 | Missing Values: 77096 | Percentage: 13.06%
Column: V54 | Missing Values: 77096 | Percentage: 13.06%
Column: V55 | Missing Values: 77096 | Percentage: 13.06%
Column: V56 | Missing Values: 77096 | Percentage: 13.06%
Column: V57 | Missing Values: 77096 | Percentage: 13.06%
Column: V58 | Missing Values: 77096 | Percentage: 13.06%
Column: V59 | Missing Values: 77096 | Percentage: 13.06%
Column: V60 | Missing Values: 77096 | Percentage: 13.06%
Column: V61 | Missing Values: 77096 | Percentage: 13.06%
Column: V62 | Missing Values: 77096 | Percentage: 13.06%
Column: V63 | Missing Values: 77096 | Percentage: 13.06%
Column: V64 | Missing Values: 77096 | Percentage: 13.06%
Column: V65 | Missing Values: 77096 | Percentage: 13.06%
Column: V66 | Missing Values: 77096 | Percentage: 13.06%
Column: V67 | Missing Values: 77096 | Percentage: 13.06%
Column: V68 | Missing Values: 77096 | Percentage: 13.06%
Column: V69 | Missing Values: 77096 | Percentage: 13.06%
Column: V70 | Missing Values: 77096 | Percentage: 13.06%
Column: V71 | Missing Values: 77096 | Percentage: 13.06%
Column: V72 | Missing Values: 77096 | Percentage: 13.06%
Column: V73 | Missing Values: 77096 | Percentage: 13.06%
Column: V74 | Missing Values: 77096 | Percentage: 13.06%
Column: V75 | Missing Values: 89164 | Percentage: 15.10%
Column: V76 | Missing Values: 89164 | Percentage: 15.10%
Column: V77 | Missing Values: 89164 | Percentage: 15.10%
Column: V78 | Missing Values: 89164 | Percentage: 15.10%
Column: V79 | Missing Values: 89164 | Percentage: 15.10%
Column: V80 | Missing Values: 89164 | Percentage: 15.10%
Column: V81 | Missing Values: 89164 | Percentage: 15.10%
Column: V82 | Missing Values: 89164 | Percentage: 15.10%
Column: V83 | Missing Values: 89164 | Percentage: 15.10%
Column: V84 | Missing Values: 89164 | Percentage: 15.10%
Column: V85 | Missing Values: 89164 | Percentage: 15.10%
Column: V86 | Missing Values: 89164 | Percentage: 15.10%
Column: V87 | Missing Values: 89164 | Percentage: 15.10%
Column: V88 | Missing Values: 89164 | Percentage: 15.10%
Column: V89 | Missing Values: 89164 | Percentage: 15.10%
Column: V90 | Missing Values: 89164 | Percentage: 15.10%
Column: V91 | Missing Values: 89164 | Percentage: 15.10%
Column: V92 | Missing Values: 89164 | Percentage: 15.10%
Column: V93 | Missing Values: 89164 | Percentage: 15.10%
Column: V94 | Missing Values: 89164 | Percentage: 15.10%
Column: V95 | Missing Values: 314 | Percentage: 0.05%
Column: V96 | Missing Values: 314 | Percentage: 0.05%
Column: V97 | Missing Values: 314 | Percentage: 0.05%
Column: V98 | Missing Values: 314 | Percentage: 0.05%
Column: V99 | Missing Values: 314 | Percentage: 0.05%
Column: V100 | Missing Values: 314 | Percentage: 0.05%
Column: V101 | Missing Values: 314 | Percentage: 0.05%
Column: V102 | Missing Values: 314 | Percentage: 0.05%
Column: V103 | Missing Values: 314 | Percentage: 0.05%
Column: V104 | Missing Values: 314 | Percentage: 0.05%
Column: V105 | Missing Values: 314 | Percentage: 0.05%
Column: V106 | Missing Values: 314 | Percentage: 0.05%
Column: V107 | Missing Values: 314 | Percentage: 0.05%
Column: V108 | Missing Values: 314 | Percentage: 0.05%
Column: V109 | Missing Values: 314 | Percentage: 0.05%
Column: V110 | Missing Values: 314 | Percentage: 0.05%
Column: V111 | Missing Values: 314 | Percentage: 0.05%
Column: V112 | Missing Values: 314 | Percentage: 0.05%
Column: V113 | Missing Values: 314 | Percentage: 0.05%
Column: V114 | Missing Values: 314 | Percentage: 0.05%
Column: V115 | Missing Values: 314 | Percentage: 0.05%
Column: V116 | Missing Values: 314 | Percentage: 0.05%
Column: V117 | Missing Values: 314 | Percentage: 0.05%
Column: V118 | Missing Values: 314 | Percentage: 0.05%
Column: V119 | Missing Values: 314 | Percentage: 0.05%
Column: V120 | Missing Values: 314 | Percentage: 0.05%
Column: V121 | Missing Values: 314 | Percentage: 0.05%
Column: V122 | Missing Values: 314 | Percentage: 0.05%
Column: V123 | Missing Values: 314 | Percentage: 0.05%
Column: V124 | Missing Values: 314 | Percentage: 0.05%
Column: V125 | Missing Values: 314 | Percentage: 0.05%
Column: V126 | Missing Values: 314 | Percentage: 0.05%
Column: V127 | Missing Values: 314 | Percentage: 0.05%
Column: V128 | Missing Values: 314 | Percentage: 0.05%
Column: V129 | Missing Values: 314 | Percentage: 0.05%
Column: V130 | Missing Values: 314 | Percentage: 0.05%
Column: V131 | Missing Values: 314 | Percentage: 0.05%
Column: V132 | Missing Values: 314 | Percentage: 0.05%
Column: V133 | Missing Values: 314 | Percentage: 0.05%
Column: V134 | Missing Values: 314 | Percentage: 0.05%
Column: V135 | Missing Values: 314 | Percentage: 0.05%
Column: V136 | Missing Values: 314 | Percentage: 0.05%
Column: V137 | Missing Values: 314 | Percentage: 0.05%
Column: V138 | Missing Values: 508595 | Percentage: 86.12%
Column: V139 | Missing Values: 508595 | Percentage: 86.12%
Column: V140 | Missing Values: 508595 | Percentage: 86.12%
Column: V141 | Missing Values: 508595 | Percentage: 86.12%
Column: V142 | Missing Values: 508595 | Percentage: 86.12%
Column: V143 | Missing Values: 508589 | Percentage: 86.12%
Column: V144 | Missing Values: 508589 | Percentage: 86.12%
Column: V145 | Missing Values: 508589 | Percentage: 86.12%
Column: V146 | Missing Values: 508595 | Percentage: 86.12%
Column: V147 | Missing Values: 508595 | Percentage: 86.12%
Column: V148 | Missing Values: 508595 | Percentage: 86.12%
Column: V149 | Missing Values: 508595 | Percentage: 86.12%
Column: V150 | Missing Values: 508589 | Percentage: 86.12%
Column: V151 | Missing Values: 508589 | Percentage: 86.12%
Column: V152 | Missing Values: 508589 | Percentage: 86.12%
Column: V153 | Missing Values: 508595 | Percentage: 86.12%
Column: V154 | Missing Values: 508595 | Percentage: 86.12%
Column: V155 | Missing Values: 508595 | Percentage: 86.12%
Column: V156 | Missing Values: 508595 | Percentage: 86.12%
Column: V157 | Missing Values: 508595 | Percentage: 86.12%
Column: V158 | Missing Values: 508595 | Percentage: 86.12%
Column: V159 | Missing Values: 508589 | Percentage: 86.12%
Column: V160 | Missing Values: 508589 | Percentage: 86.12%
Column: V161 | Missing Values: 508595 | Percentage: 86.12%
Column: V162 | Missing Values: 508595 | Percentage: 86.12%
Column: V163 | Missing Values: 508595 | Percentage: 86.12%
Column: V164 | Missing Values: 508589 | Percentage: 86.12%
Column: V165 | Missing Values: 508589 | Percentage: 86.12%
Column: V166 | Missing Values: 508589 | Percentage: 86.12%
Column: V167 | Missing Values: 450909 | Percentage: 76.36%
Column: V168 | Missing Values: 450909 | Percentage: 76.36%
Column: V169 | Missing Values: 450721 | Percentage: 76.32%
Column: V170 | Missing Values: 450721 | Percentage: 76.32%
Column: V171 | Missing Values: 450721 | Percentage: 76.32%
Column: V172 | Missing Values: 450909 | Percentage: 76.36%
Column: V173 | Missing Values: 450909 | Percentage: 76.36%
Column: V174 | Missing Values: 450721 | Percentage: 76.32%
Column: V175 | Missing Values: 450721 | Percentage: 76.32%
Column: V176 | Missing Values: 450909 | Percentage: 76.36%
Column: V177 | Missing Values: 450909 | Percentage: 76.36%
Column: V178 | Missing Values: 450909 | Percentage: 76.36%
Column: V179 | Missing Values: 450909 | Percentage: 76.36%
Column: V180 | Missing Values: 450721 | Percentage: 76.32%
Column: V181 | Missing Values: 450909 | Percentage: 76.36%
Column: V182 | Missing Values: 450909 | Percentage: 76.36%
Column: V183 | Missing Values: 450909 | Percentage: 76.36%
Column: V184 | Missing Values: 450721 | Percentage: 76.32%
Column: V185 | Missing Values: 450721 | Percentage: 76.32%
Column: V186 | Missing Values: 450909 | Percentage: 76.36%
Column: V187 | Missing Values: 450909 | Percentage: 76.36%
Column: V188 | Missing Values: 450721 | Percentage: 76.32%
Column: V189 | Missing Values: 450721 | Percentage: 76.32%
Column: V190 | Missing Values: 450909 | Percentage: 76.36%
Column: V191 | Missing Values: 450909 | Percentage: 76.36%
Column: V192 | Missing Values: 450909 | Percentage: 76.36%
Column: V193 | Missing Values: 450909 | Percentage: 76.36%
Column: V194 | Missing Values: 450721 | Percentage: 76.32%
Column: V195 | Missing Values: 450721 | Percentage: 76.32%
Column: V196 | Missing Values: 450909 | Percentage: 76.36%
Column: V197 | Missing Values: 450721 | Percentage: 76.32%
Column: V198 | Missing Values: 450721 | Percentage: 76.32%
Column: V199 | Missing Values: 450909 | Percentage: 76.36%
Column: V200 | Missing Values: 450721 | Percentage: 76.32%
Column: V201 | Missing Values: 450721 | Percentage: 76.32%
Column: V202 | Missing Values: 450909 | Percentage: 76.36%
Column: V203 | Missing Values: 450909 | Percentage: 76.36%
Column: V204 | Missing Values: 450909 | Percentage: 76.36%
Column: V205 | Missing Values: 450909 | Percentage: 76.36%
Column: V206 | Missing Values: 450909 | Percentage: 76.36%
Column: V207 | Missing Values: 450909 | Percentage: 76.36%
Column: V208 | Missing Values: 450721 | Percentage: 76.32%
Column: V209 | Missing Values: 450721 | Percentage: 76.32%
Column: V210 | Missing Values: 450721 | Percentage: 76.32%
Column: V211 | Missing Values: 450909 | Percentage: 76.36%
Column: V212 | Missing Values: 450909 | Percentage: 76.36%
Column: V213 | Missing Values: 450909 | Percentage: 76.36%
Column: V214 | Missing Values: 450909 | Percentage: 76.36%
Column: V215 | Missing Values: 450909 | Percentage: 76.36%
Column: V216 | Missing Values: 450909 | Percentage: 76.36%
Column: V217 | Missing Values: 460110 | Percentage: 77.91%
Column: V218 | Missing Values: 460110 | Percentage: 77.91%
Column: V219 | Missing Values: 460110 | Percentage: 77.91%
Column: V220 | Missing Values: 449124 | Percentage: 76.05%
Column: V221 | Missing Values: 449124 | Percentage: 76.05%
Column: V222 | Missing Values: 449124 | Percentage: 76.05%
Column: V223 | Missing Values: 460110 | Percentage: 77.91%
Column: V224 | Missing Values: 460110 | Percentage: 77.91%
Column: V225 | Missing Values: 460110 | Percentage: 77.91%
Column: V226 | Missing Values: 460110 | Percentage: 77.91%
Column: V227 | Missing Values: 449124 | Percentage: 76.05%
Column: V228 | Missing Values: 460110 | Percentage: 77.91%
Column: V229 | Missing Values: 460110 | Percentage: 77.91%
Column: V230 | Missing Values: 460110 | Percentage: 77.91%
Column: V231 | Missing Values: 460110 | Percentage: 77.91%
Column: V232 | Missing Values: 460110 | Percentage: 77.91%
Column: V233 | Missing Values: 460110 | Percentage: 77.91%
Column: V234 | Missing Values: 449124 | Percentage: 76.05%
Column: V235 | Missing Values: 460110 | Percentage: 77.91%
Column: V236 | Missing Values: 460110 | Percentage: 77.91%
Column: V237 | Missing Values: 460110 | Percentage: 77.91%
Column: V238 | Missing Values: 449124 | Percentage: 76.05%
Column: V239 | Missing Values: 449124 | Percentage: 76.05%
Column: V240 | Missing Values: 460110 | Percentage: 77.91%
Column: V241 | Missing Values: 460110 | Percentage: 77.91%
Column: V242 | Missing Values: 460110 | Percentage: 77.91%
Column: V243 | Missing Values: 460110 | Percentage: 77.91%
Column: V244 | Missing Values: 460110 | Percentage: 77.91%
Column: V245 | Missing Values: 449124 | Percentage: 76.05%
Column: V246 | Missing Values: 460110 | Percentage: 77.91%
Column: V247 | Missing Values: 460110 | Percentage: 77.91%
Column: V248 | Missing Values: 460110 | Percentage: 77.91%
Column: V249 | Missing Values: 460110 | Percentage: 77.91%
Column: V250 | Missing Values: 449124 | Percentage: 76.05%
Column: V251 | Missing Values: 449124 | Percentage: 76.05%
Column: V252 | Missing Values: 460110 | Percentage: 77.91%
Column: V253 | Missing Values: 460110 | Percentage: 77.91%
Column: V254 | Missing Values: 460110 | Percentage: 77.91%
Column: V255 | Missing Values: 449124 | Percentage: 76.05%
Column: V256 | Missing Values: 449124 | Percentage: 76.05%
Column: V257 | Missing Values: 460110 | Percentage: 77.91%
Column: V258 | Missing Values: 460110 | Percentage: 77.91%
Column: V259 | Missing Values: 449124 | Percentage: 76.05%
Column: V260 | Missing Values: 460110 | Percentage: 77.91%
Column: V261 | Missing Values: 460110 | Percentage: 77.91%
Column: V262 | Missing Values: 460110 | Percentage: 77.91%
Column: V263 | Missing Values: 460110 | Percentage: 77.91%
Column: V264 | Missing Values: 460110 | Percentage: 77.91%
Column: V265 | Missing Values: 460110 | Percentage: 77.91%
Column: V266 | Missing Values: 460110 | Percentage: 77.91%
Column: V267 | Missing Values: 460110 | Percentage: 77.91%
Column: V268 | Missing Values: 460110 | Percentage: 77.91%
Column: V269 | Missing Values: 460110 | Percentage: 77.91%
Column: V270 | Missing Values: 449124 | Percentage: 76.05%
Column: V271 | Missing Values: 449124 | Percentage: 76.05%
Column: V272 | Missing Values: 449124 | Percentage: 76.05%
Column: V273 | Missing Values: 460110 | Percentage: 77.91%
Column: V274 | Missing Values: 460110 | Percentage: 77.91%
Column: V275 | Missing Values: 460110 | Percentage: 77.91%
Column: V276 | Missing Values: 460110 | Percentage: 77.91%
Column: V277 | Missing Values: 460110 | Percentage: 77.91%
Column: V278 | Missing Values: 460110 | Percentage: 77.91%
Column: V279 | Missing Values: 12 | Percentage: 0.00%
Column: V280 | Missing Values: 12 | Percentage: 0.00%
Column: V281 | Missing Values: 1269 | Percentage: 0.21%
Column: V282 | Missing Values: 1269 | Percentage: 0.21%
Column: V283 | Missing Values: 1269 | Percentage: 0.21%
Column: V284 | Missing Values: 12 | Percentage: 0.00%
Column: V285 | Missing Values: 12 | Percentage: 0.00%
Column: V286 | Missing Values: 12 | Percentage: 0.00%
Column: V287 | Missing Values: 12 | Percentage: 0.00%
Column: V288 | Missing Values: 1269 | Percentage: 0.21%
Column: V289 | Missing Values: 1269 | Percentage: 0.21%
Column: V290 | Missing Values: 12 | Percentage: 0.00%
Column: V291 | Missing Values: 12 | Percentage: 0.00%
Column: V292 | Missing Values: 12 | Percentage: 0.00%
Column: V293 | Missing Values: 12 | Percentage: 0.00%

In [11]:
#Column wise anlaysis:
for col in (train_transaction.columns):
    if train_transaction[col].isnull().sum() == 0:
        print(f"The nunique: {train_transaction[col].nunique()} | Column: {col} | Data Type: {train_transaction[col].dtype}")

        print(f'This is the column which contains absolute non-zero: {col}')

The nunique: 590540 | Column: TransactionID | Data Type: int64
This is the column which contains absolute non-zero: TransactionID
The nunique: 2 | Column: isFraud | Data Type: int64
This is the column which contains absolute non-zero: isFraud
The nunique: 573349 | Column: TransactionDT | Data Type: int64
This is the column which contains absolute non-zero: TransactionDT
The nunique: 20902 | Column: TransactionAmt | Data Type: float64
This is the column which contains absolute non-zero: TransactionAmt
The nunique: 5 | Column: ProductCD | Data Type: str
This is the column which contains absolute non-zero: ProductCD
The nunique: 13553 | Column: card1 | Data Type: int64
This is the column which contains absolute non-zero: card1
The nunique: 1657 | Column: C1 | Data Type: float64
This is the column which contains absolute non-zero: C1
The nunique: 1216 | Column: C2 | Data Type: float64
This is the column which contains absolute non-zero: C2
The nunique: 27 | Column: C3 | Data Type: float64
This is the column which contains absolute non-zero: C3
The nunique: 1260 | Column: C4 | Data Type: float64
This is the column which contains absolute non-zero: C4
The nunique: 319 | Column: C5 | Data Type: float64
This is the column which contains absolute non-zero: C5
The nunique: 1328 | Column: C6 | Data Type: float64
This is the column which contains absolute non-zero: C6
The nunique: 1103 | Column: C7 | Data Type: float64
This is the column which contains absolute non-zero: C7
The nunique: 1253 | Column: C8 | Data Type: float64
This is the column which contains absolute non-zero: C8
The nunique: 205 | Column: C9 | Data Type: float64
This is the column which contains absolute non-zero: C9
The nunique: 1231 | Column: C10 | Data Type: float64
This is the column which contains absolute non-zero: C10
The nunique: 1476 | Column: C11 | Data Type: float64
This is the column which contains absolute non-zero: C11
The nunique: 1199 | Column: C12 | Data Type: float64
This is the column which contains absolute non-zero: C12
The nunique: 1597 | Column: C13 | Data Type: float64
This is the column which contains absolute non-zero: C13
The nunique: 1108 | Column: C14 | Data Type: float64
This is the column which contains absolute non-zero: C14

# **Test dataset column or target output for the dataset:**

In [12]:
train_identity = pd.read_csv(r'C:\Users\acer\Desktop\Programs\Projects_for _data_science\Fraud_Detection_Model\data\01_raw\test_transaction.csv')

In [13]:
train_identity.head()

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,3663549,18403224,31.95,W,10409,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3663550,18403263,49.00,W,4272,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3663551,18403310,171.00,W,4476,574.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3663552,18403310,284.95,W,10989,360.0,150.0,visa,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3663553,18403317,67.95,W,18018,452.0,150.0,mastercard,117.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Every concept goes in a way that, there is to be a combination of the dataset:
Consisting in a way: transaction + indentity

In [14]:
train = train_transaction.merge(train_identity,on='TransactionID',how='left')

In [15]:
train_identity.head()

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,3663549,18403224,31.95,W,10409,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3663550,18403263,49.00,W,4272,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3663551,18403310,171.00,W,4476,574.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3663552,18403310,284.95,W,10989,360.0,150.0,visa,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3663553,18403317,67.95,W,18018,452.0,150.0,mastercard,117.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
train

,TransactionID,isFraud,TransactionDT_x,TransactionAmt_x,ProductCD_x,card1_x,card2_x,card3_x,card4_x,card5_x,...,V330_y,V331_y,V332_y,V333_y,V334_y,V335_y,V336_y,V337_y,V338_y,V339_y
0,2987000,0,86400,68.50,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.00,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.00,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.00,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.00,H,4497,514.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590535,3577535,0,15811047,49.00,W,6550,NaN,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590536,3577536,0,15811049,39.50,W,10444,225.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590537,3577537,0,15811079,30.95,W,12037,595.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590538,3577538,0,15811088,117.00,W,7826,481.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590539,3577539,0,15811131,279.95,W,15066,170.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# **TEST DATASET** : Combination of test Dataset : transaction and identity.

In [17]:
test_transaction = pd.read_csv(r'C:\Users\acer\Desktop\Programs\Projects_for _data_science\Fraud_Detection_Model\data\01_raw\test_transaction.csv')

In [18]:
test_transaction.sample(10)

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
136794,3800343,23129726,26.950,W,7508,321.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284360,3947909,28252941,15.000,S,6457,321.0,150.0,visa,195.0,debit,...,0.0,10.0,55.0,26.0,10.0,55.0,26.0,0.0,0.0,0.0
259156,3922705,27384216,5.656,C,13832,375.0,185.0,mastercard,224.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410274,4073823,32129374,25.950,W,5033,269.0,150.0,mastercard,224.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76508,3740057,21039333,201.000,W,17055,393.0,150.0,mastercard,117.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190634,3854183,25030507,117.000,W,7207,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95208,3758757,21597399,34.000,W,11523,555.0,150.0,mastercard,224.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209975,3873524,25746922,47.950,W,12544,321.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356153,4019702,30579913,49.000,W,6019,583.0,150.0,visa,226.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352447,4015996,30464550,87.950,W,12544,321.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
test_identity = pd.read_csv(r'C:\Users\acer\Desktop\Programs\Projects_for _data_science\Fraud_Detection_Model\data\01_raw\test_identity.csv')

In [20]:
test_identity.sample(10)

,TransactionID,id-01,id-02,id-03,id-04,id-05,id-06,id-07,id-08,id-09,...,id-31,id-32,id-33,id-34,id-35,id-36,id-37,id-38,DeviceType,DeviceInfo
95678,4080033,-5.0,49175.0,NaN,NaN,0.0,0.0,NaN,NaN,0.0,...,chrome 70.0,24.0,1280x720,match_status:2,T,F,T,T,desktop,Windows
41900,3887448,-15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24460,3795776,-5.0,13688.0,0.0,0.0,5.0,-18.0,NaN,NaN,0.0,...,chrome 68.0,24.0,1680x1050,match_status:2,T,F,T,T,desktop,Windows
124981,4139013,-5.0,264921.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,mobile safari 12.0,32.0,2001x1125,match_status:2,T,F,F,F,mobile,iOS Device
47284,3910849,-10.0,222083.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 69.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-A320FL Build/R16NW
84265,4045077,-5.0,323058.0,0.0,0.0,0.0,-2.0,NaN,NaN,0.0,...,chrome 65.0,NaN,NaN,NaN,F,F,T,F,desktop,NaN
104490,4100840,-5.0,21256.0,NaN,NaN,2.0,0.0,NaN,NaN,NaN,...,chrome 71.0,24.0,1920x1080,match_status:2,T,F,T,T,desktop,Windows
12407,3731479,-5.0,103849.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,2208x1242,match_status:2,T,F,F,F,mobile,iOS Device
22079,3783017,-5.0,339680.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,2001x1125,match_status:2,T,F,F,F,mobile,iOS Device
24738,3797197,-5.0,110771.0,0.0,0.0,0.0,-1.0,NaN,NaN,0.0,...,chrome 68.0,24.0,1920x1080,match_status:2,T,F,T,F,desktop,Windows

In [21]:
test = test_transaction.merge(test_identity,on='TransactionID',how='left')

In [22]:
test.sample(10)

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,id-31,id-32,id-33,id-34,id-35,id-36,id-37,id-38,DeviceType,DeviceInfo
224330,3887879,26257774,57.950,W,5964,268.0,150.0,visa,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
468852,4132401,33430964,50.000,H,14641,399.0,150.0,american express,118.0,credit,...,safari 10.0,NaN,NaN,match_status:2,T,T,F,T,desktop,NaN
135669,3799218,23072976,14.386,C,5365,177.0,185.0,mastercard,224.0,credit,...,safari 11.0,NaN,NaN,NaN,F,F,T,F,desktop,NaN
145780,3809329,23468922,49.000,W,18249,360.0,150.0,mastercard,126.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
430219,4093768,32646310,125.000,R,16078,203.0,150.0,mastercard,195.0,credit,...,mobile safari 11.0,32.0,2224x1668,match_status:2,T,F,F,F,mobile,iOS Device
308636,3972185,29081042,206.000,W,13249,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159441,3822990,23911510,226.000,W,14182,562.0,150.0,mastercard,102.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23907,3687456,19216624,117.000,W,9480,476.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319511,3983060,29371096,159.950,W,5815,268.0,150.0,visa,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29612,3693161,19412591,57.950,W,6951,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Transforming into intermediate as a specific data type: Using pickling

In [23]:
import pickle

In [24]:
#training data is transformed into a pickle file for further processing and analysis.


train.to_pickle(r'C:\Users\acer\Desktop\Programs\Projects_for _data_science\Fraud_Detection_Model\data\02_intermediate\train.pkl')

In [25]:
# testing data is transformed into a pickle file for further processing and analysis.

test.to_pickle(r'C:\Users\acer\Desktop\Programs\Projects_for _data_science\Fraud_Detection_Model\data\02_intermediate\test.pkl')

# Finally, we have transformed our dataset into a whole new format consisting  all the required features and its target, collectively.

# Hence, our part of data ingestion is done till now after the integration of our whole dataset which is now ready to be processed further in its respective operational field.